/* The following code was generated by JFlex 1.4.3 on 5/25/13 2:43 AM */

package compiler2013.syntactic;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 5/25/13 2:43 AM from the specification file
 * <tt>spcompiler.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner, Symbols {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYSTRING = 2;
  public static final int YYINITIAL = 0;
  public static final int YYCHAR = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\71\1\1\1\0\1\3\1\2\22\0\1\3\1\61\1\15"+
    "\1\6\1\7\1\57\1\66\1\16\1\44\1\45\1\5\1\55\1\52"+
    "\1\56\1\54\1\4\1\11\7\12\2\10\1\0\1\53\1\63\1\60"+
    "\1\64\2\0\6\14\21\7\1\13\2\7\1\50\1\70\1\51\1\67"+
    "\1\7\1\0\1\32\1\41\1\30\1\23\1\22\1\24\1\7\1\31"+
    "\1\27\1\7\1\42\1\37\1\7\1\34\1\26\1\21\1\7\1\33"+
    "\1\35\1\17\1\36\1\25\1\40\1\13\1\20\1\43\1\46\1\65"+
    "\1\47\1\62\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\1\1\1\5\2\6"+
    "\1\7\1\10\13\5\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\0\1\37\1\40\3\0\1\41\1\42\1\0"+
    "\2\43\1\44\1\0\4\5\1\45\11\5\1\0\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\1\61\1\62\1\63\1\64\1\65\1\66"+
    "\1\67\1\70\1\71\1\72\1\73\1\74\1\75\1\76"+
    "\1\77\1\100\1\0\1\101\2\5\1\102\1\5\1\103"+
    "\10\5\1\104\1\105\1\106\1\0\1\5\1\107\1\110"+
    "\1\5\1\111\13\5\1\112\1\113\1\114\2\5\1\115"+
    "\1\116\1\117\1\120\1\5\1\121";

  private static int [] zzUnpackAction() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\256\0\256\0\350\0\u0122\0\u015c"+
    "\0\u0196\0\u01d0\0\u020a\0\u0244\0\256\0\256\0\u027e\0\u02b8"+
    "\0\u02f2\0\u032c\0\u0366\0\u03a0\0\u03da\0\u0414\0\u044e\0\u0488"+
    "\0\u04c2\0\256\0\256\0\256\0\256\0\256\0\256\0\256"+
    "\0\256\0\u04fc\0\u0536\0\u0570\0\u05aa\0\u05e4\0\u061e\0\256"+
    "\0\u0658\0\u0692\0\u06cc\0\u0706\0\u0740\0\u077a\0\256\0\u07b4"+
    "\0\256\0\256\0\u07ee\0\u0828\0\u0862\0\256\0\256\0\u0196"+
    "\0\256\0\u089c\0\u08d6\0\u0910\0\u094a\0\u0984\0\u09be\0\u09f8"+
    "\0\u01d0\0\u0a32\0\u0a6c\0\u0aa6\0\u0ae0\0\u0b1a\0\u0b54\0\u0b8e"+
    "\0\u0bc8\0\u0c02\0\u0c3c\0\256\0\256\0\256\0\256\0\256"+
    "\0\256\0\256\0\256\0\256\0\u0c76\0\256\0\u0cb0\0\256"+
    "\0\256\0\256\0\256\0\256\0\256\0\256\0\256\0\256"+
    "\0\256\0\256\0\256\0\256\0\256\0\256\0\u0cea\0\u0d24"+
    "\0\u0d5e\0\u0d98\0\u01d0\0\u0dd2\0\u01d0\0\u0e0c\0\u0e46\0\u0e80"+
    "\0\u0eba\0\u0ef4\0\u0f2e\0\u0f68\0\u0fa2\0\256\0\256\0\256"+
    "\0\u0fdc\0\u1016\0\u01d0\0\u01d0\0\u1050\0\u01d0\0\u108a\0\u10c4"+
    "\0\u10fe\0\u1138\0\u1172\0\u11ac\0\u11e6\0\u1220\0\u125a\0\u1294"+
    "\0\u12ce\0\u01d0\0\u01d0\0\u01d0\0\u1308\0\u1342\0\u01d0\0\u01d0"+
    "\0\u01d0\0\u01d0\0\u137c\0\u01d0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\5\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\13\2\12\1\15\1\16\1\17\2\12"+
    "\1\20\1\12\1\21\1\22\1\12\1\23\1\24\2\12"+
    "\1\25\1\12\1\26\1\27\1\12\1\30\1\31\2\12"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\1\4\1\5\1\56\2\0"+
    "\12\56\1\57\52\56\1\60\1\0\1\61\2\0\13\61"+
    "\1\62\51\61\1\63\74\0\1\5\74\0\1\64\1\65"+
    "\52\0\1\66\71\0\1\67\11\0\1\70\1\71\1\72"+
    "\67\70\7\0\6\12\2\0\25\12\36\0\3\13\71\0"+
    "\1\73\1\74\65\0\6\12\2\0\1\12\1\75\23\12"+
    "\35\0\6\12\2\0\20\12\1\76\4\12\35\0\6\12"+
    "\2\0\7\12\1\77\15\12\35\0\6\12\2\0\7\12"+
    "\1\100\15\12\35\0\6\12\2\0\5\12\1\101\7\12"+
    "\1\102\7\12\35\0\6\12\2\0\7\12\1\103\2\12"+
    "\1\104\12\12\35\0\6\12\2\0\3\12\1\105\21\12"+
    "\35\0\6\12\2\0\1\106\7\12\1\107\14\12\35\0"+
    "\6\12\2\0\15\12\1\110\7\12\35\0\6\12\2\0"+
    "\12\12\1\111\12\12\35\0\6\12\2\0\14\12\1\112"+
    "\10\12\102\0\1\113\72\0\1\114\2\0\1\115\67\0"+
    "\1\116\1\0\1\117\3\0\1\120\65\0\1\121\71\0"+
    "\1\122\71\0\1\123\71\0\1\124\2\0\1\125\66\0"+
    "\1\126\3\0\1\127\65\0\1\130\4\0\1\131\64\0"+
    "\1\132\5\0\1\133\63\0\1\134\11\0\1\56\2\0"+
    "\12\56\1\0\52\56\17\0\1\135\1\0\1\136\13\0"+
    "\1\137\1\140\33\0\1\141\17\0\1\142\1\143\13\0"+
    "\1\144\1\145\33\0\1\146\1\0\1\64\1\5\1\6"+
    "\67\64\72\147\1\0\1\71\101\0\2\73\67\0\1\150"+
    "\1\0\1\150\1\0\1\150\5\0\3\150\3\0\1\150"+
    "\1\0\1\150\6\0\1\150\37\0\6\12\2\0\2\12"+
    "\1\151\22\12\35\0\6\12\2\0\16\12\1\152\6\12"+
    "\35\0\6\12\2\0\14\12\1\153\10\12\35\0\6\12"+
    "\2\0\10\12\1\154\14\12\35\0\6\12\2\0\1\155"+
    "\24\12\35\0\6\12\2\0\15\12\1\156\7\12\35\0"+
    "\6\12\2\0\13\12\1\157\11\12\35\0\6\12\2\0"+
    "\1\160\24\12\35\0\6\12\2\0\14\12\1\161\10\12"+
    "\35\0\6\12\2\0\24\12\1\162\35\0\6\12\2\0"+
    "\10\12\1\163\14\12\35\0\6\12\2\0\10\12\1\164"+
    "\14\12\35\0\6\12\2\0\3\12\1\165\21\12\102\0"+
    "\1\166\75\0\1\167\71\0\1\170\11\0\5\147\1\171"+
    "\64\147\10\0\3\150\1\0\1\150\5\0\3\150\3\0"+
    "\1\150\1\0\1\150\6\0\1\150\37\0\6\12\2\0"+
    "\3\12\1\172\21\12\35\0\6\12\2\0\3\12\1\173"+
    "\21\12\35\0\6\12\2\0\4\12\1\174\20\12\35\0"+
    "\6\12\2\0\1\175\24\12\35\0\6\12\2\0\14\12"+
    "\1\176\10\12\35\0\6\12\2\0\17\12\1\177\5\12"+
    "\35\0\6\12\2\0\17\12\1\200\5\12\35\0\6\12"+
    "\2\0\3\12\1\201\21\12\35\0\6\12\2\0\7\12"+
    "\1\202\15\12\35\0\6\12\2\0\20\12\1\203\4\12"+
    "\35\0\6\12\2\0\13\12\1\204\11\12\26\0\4\147"+
    "\1\5\1\171\64\147\7\0\6\12\2\0\4\12\1\205"+
    "\20\12\35\0\6\12\2\0\10\12\1\206\14\12\35\0"+
    "\6\12\2\0\14\12\1\207\10\12\35\0\6\12\2\0"+
    "\11\12\1\210\13\12\35\0\6\12\2\0\7\12\1\211"+
    "\15\12\35\0\6\12\2\0\15\12\1\212\7\12\35\0"+
    "\6\12\2\0\3\12\1\213\21\12\35\0\6\12\2\0"+
    "\23\12\1\214\1\12\35\0\6\12\2\0\3\12\1\215"+
    "\21\12\35\0\6\12\2\0\15\12\1\216\7\12\35\0"+
    "\6\12\2\0\15\12\1\217\7\12\35\0\6\12\2\0"+
    "\1\220\24\12\35\0\6\12\2\0\5\12\1\221\17\12"+
    "\35\0\6\12\2\0\5\12\1\222\17\12\35\0\6\12"+
    "\2\0\17\12\1\223\5\12\35\0\6\12\2\0\3\12"+
    "\1\224\21\12\26\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5046];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\2\11\7\1\2\11\13\1\10\11\6\1\1\11"+
    "\6\1\1\11\1\0\2\11\3\0\2\11\1\0\1\11"+
    "\2\1\1\0\16\1\1\0\11\11\1\1\1\11\1\1"+
    "\17\11\1\0\16\1\3\11\1\0\33\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	StringBuffer string = new StringBuffer();
	char ch;
	int flag = 0;

	private void err(String message) {
		System.out.println("Scanning error in line " + yyline + ", column " + yycolumn + ": " + message);
	}

	private int octToDec(String s) {
		int ans = 0, x = 1;
		for (int i = s.length() - 1; i >= 1; --i) {
			ans += (s.charAt(i) - '0') * x;
			x *= 8;
		}
		return ans;
	}

	private int hexToDec(String s) {
		int ans = 0, x = 1;
		for (int i = s.length() - 1; i >= 1; --i) {
			if (s.charAt(i) >= '0' && s.charAt(i) <= '9') ans += (s.charAt(i) - '0') * x;
			else if (s.charAt(i) >= 'A' && s.charAt(i) <= 'F') ans += (s.charAt(i) - 'A' + 10) * x;
			else if (s.charAt(i) >= 'a' && s.charAt(i) <= 'f') ans += (s.charAt(i) - 'a' + 10) * x;
			x *= 16;
		}
		return ans;
	}

	private java_cup.runtime.Symbol tok(int kind) {
		return new java_cup.runtime.Symbol(kind, yyline, yycolumn);
	}

	private java_cup.runtime.Symbol tok(int kind, Object value) {
		return new java_cup.runtime.Symbol(kind, yyline, yycolumn, value);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 146) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 77: 
          { return tok(RETURN);
          }
        case 82: break;
        case 42: 
          { return tok(PTR);
          }
        case 83: break;
        case 81: 
          { return tok(CONTINUE);
          }
        case 84: break;
        case 15: 
          { return tok(COMMAR);
          }
        case 85: break;
        case 5: 
          { if (ParserTest.isTypeId(yytext())) return tok(TYPEID, yytext());
		else return tok(ID, yytext());
          }
        case 86: break;
        case 11: 
          { return tok(LBRACE);
          }
        case 87: break;
        case 17: 
          { return tok(DOT);
          }
        case 88: break;
        case 67: 
          { return tok(INT);
          }
        case 89: break;
        case 51: 
          { return tok(PARAOR);
          }
        case 90: break;
        case 41: 
          { return tok(SUB_ASSIGN);
          }
        case 91: break;
        case 27: 
          { return tok(AND);
          }
        case 92: break;
        case 68: 
          { return tok(ELLIPSIS);
          }
        case 93: break;
        case 49: 
          { return tok(SHR);
          }
        case 94: break;
        case 39: 
          { return tok(ADD_ASSIGN);
          }
        case 95: break;
        case 58: 
          { string.append('\n');
          }
        case 96: break;
        case 52: 
          { return tok(AND_ASSIGN);
          }
        case 97: break;
        case 55: 
          { string.append('\"');
          }
        case 98: break;
        case 73: 
          { return tok(CHAR);
          }
        case 99: break;
        case 75: 
          { return tok(WHILE);
          }
        case 100: break;
        case 22: 
          { return tok(NOT);
          }
        case 101: break;
        case 25: 
          { return tok(GT);
          }
        case 102: break;
        case 44: 
          { return tok(EQ);
          }
        case 103: break;
        case 16: 
          { return tok(SEMICOLON);
          }
        case 104: break;
        case 69: 
          { return tok(SHL_ASSIGN);
          }
        case 105: break;
        case 57: 
          { string.append('\r');
          }
        case 106: break;
        case 3: 
          { return tok(DIVIDE);
          }
        case 107: break;
        case 50: 
          { return tok(OR_ASSIGN);
          }
        case 108: break;
        case 74: 
          { return tok(UNION);
          }
        case 109: break;
        case 56: 
          { string.append('\t');
          }
        case 110: break;
        case 47: 
          { return tok(SHL);
          }
        case 111: break;
        case 24: 
          { return tok(LT);
          }
        case 112: break;
        case 10: 
          { return tok(RPAREN);
          }
        case 113: break;
        case 40: 
          { return tok(DEC);
          }
        case 114: break;
        case 28: 
          { return tok(XOR);
          }
        case 115: break;
        case 21: 
          { return tok(ASSIGN);
          }
        case 116: break;
        case 54: 
          { return tok(XOR_ASSIGN);
          }
        case 117: break;
        case 33: 
          { return tok(DIV_ASSIGN);
          }
        case 118: break;
        case 64: 
          { if (flag != 0) throw new RuntimeException("Char can hold only one character");
		else {
			ch = '\\'; flag = 1;
		}
          }
        case 119: break;
        case 43: 
          { return tok(MOD_ASSIGN);
          }
        case 120: break;
        case 8: 
          { flag = 0; yybegin(YYCHAR);
          }
        case 121: break;
        case 26: 
          { return tok(OR);
          }
        case 122: break;
        case 4: 
          { return tok(TIMES);
          }
        case 123: break;
        case 29: 
          { string.append(yytext());
          }
        case 124: break;
        case 72: 
          { return tok(VOID);
          }
        case 125: break;
        case 70: 
          { return tok(SHR_ASSIGN);
          }
        case 126: break;
        case 14: 
          { return tok(RBRAKET);
          }
        case 127: break;
        case 9: 
          { return tok(LPAREN);
          }
        case 128: break;
        case 71: 
          { return tok(ELSE);
          }
        case 129: break;
        case 1: 
          { throw new RuntimeException("Illegal character " + yytext() + " in line " + (yyline + 1) + ", column " + (yycolumn + 1));
          }
        case 130: break;
        case 63: 
          { if (flag != 0) throw new RuntimeException("Char can hold only one character");
		else {
			ch = '\n'; flag = 1;
		}
          }
        case 131: break;
        case 38: 
          { return tok(INC);
          }
        case 132: break;
        case 36: 
          { return tok(NUM, new Integer(octToDec(yytext())));
          }
        case 133: break;
        case 2: 
          { /* skip */
          }
        case 134: break;
        case 48: 
          { return tok(GE);
          }
        case 135: break;
        case 61: 
          { if (flag != 0) throw new RuntimeException("Char can hold only one character");
		else {
			ch = '\t'; flag = 1;
		}
          }
        case 136: break;
        case 37: 
          { return tok(IF);
          }
        case 137: break;
        case 65: 
          { return tok(NUM, new Integer(hexToDec(yytext())));
          }
        case 138: break;
        case 13: 
          { return tok(LBRAKET);
          }
        case 139: break;
        case 59: 
          { string.append('\\');
          }
        case 140: break;
        case 45: 
          { return tok(NE) ;
          }
        case 141: break;
        case 7: 
          { string.setLength(0); yybegin(YYSTRING);
          }
        case 142: break;
        case 66: 
          { return tok(FOR);
          }
        case 143: break;
        case 60: 
          { if (flag != 0) throw new RuntimeException("Char can hold only one character");
		else {
			ch = '\''; flag = 1;
		}
          }
        case 144: break;
        case 23: 
          { return tok(TIDLE);
          }
        case 145: break;
        case 30: 
          { yybegin(YYINITIAL); return tok(STRING, string.toString());
          }
        case 146: break;
        case 46: 
          { return tok(LE);
          }
        case 147: break;
        case 76: 
          { return tok(BREAK);
          }
        case 148: break;
        case 53: 
          { return tok(PARAAND);
          }
        case 149: break;
        case 6: 
          { return tok(NUM, new Integer(yytext()));
          }
        case 150: break;
        case 31: 
          { if (flag != 0) throw new RuntimeException("Char can hold only one character");
		else {
			ch = yytext().charAt(0); flag = 1;
		}
          }
        case 151: break;
        case 32: 
          { yybegin(YYINITIAL); flag = 0; return tok(CHARCONST, ch);
          }
        case 152: break;
        case 20: 
          { return tok(MOD);
          }
        case 153: break;
        case 78: 
          { return tok(STRUCT);
          }
        case 154: break;
        case 80: 
          { return tok(TYPEDEF);
          }
        case 155: break;
        case 79: 
          { return tok(SIZEOF);
          }
        case 156: break;
        case 34: 
          { return tok(MUL_ASSIGN);
          }
        case 157: break;
        case 18: 
          { return tok(PLUS);
          }
        case 158: break;
        case 62: 
          { if (flag != 0) throw new RuntimeException("Char can hold only one character");
		else {
			ch = '\r'; flag = 1;
		}
          }
        case 159: break;
        case 19: 
          { return tok(MINUS);
          }
        case 160: break;
        case 35: 
          { 
          }
        case 161: break;
        case 12: 
          { return tok(RBRACE);
          }
        case 162: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { 	{
		if (yystate() == YYSTRING) {
			err("String boarder doesn't match");
		}
		return tok(EOF, null);
	}
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
