
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 25 02:43:12 CST 2013
//----------------------------------------------------

package compiler2013.syntactic;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int SHR_ASSIGN = 47;
  public static final int DIVIDE = 54;
  public static final int SHR = 35;
  public static final int XOR_ASSIGN = 50;
  public static final int SHL = 34;
  public static final int CHAR = 4;
  public static final int GE = 30;
  public static final int XOR = 59;
  public static final int LPAREN = 16;
  public static final int CONTINUE = 12;
  public static final int INT = 5;
  public static final int MINUS = 52;
  public static final int FOR = 11;
  public static final int PARAAND = 25;
  public static final int RPAREN = 17;
  public static final int AND = 57;
  public static final int SUB_ASSIGN = 42;
  public static final int NOT = 33;
  public static final int SEMICOLON = 23;
  public static final int SIZEOF = 15;
  public static final int TYPEID = 62;
  public static final int LT = 31;
  public static final int OR = 58;
  public static final int ELLIPSIS = 39;
  public static final int INC = 36;
  public static final int LBRAKET = 20;
  public static final int RBRAKET = 21;
  public static final int NUM = 60;
  public static final int PLUS = 51;
  public static final int TYPEDEF = 2;
  public static final int ASSIGN = 40;
  public static final int IF = 8;
  public static final int ID = 61;
  public static final int PTR = 38;
  public static final int DOT = 24;
  public static final int LE = 29;
  public static final int ADD_ASSIGN = 41;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int error = 1;
  public static final int SHL_ASSIGN = 46;
  public static final int COMMAR = 22;
  public static final int TIDLE = 56;
  public static final int MOD = 55;
  public static final int BREAK = 13;
  public static final int VOID = 3;
  public static final int EQ = 27;
  public static final int MOD_ASSIGN = 45;
  public static final int DIV_ASSIGN = 44;
  public static final int TIMES = 53;
  public static final int UNION = 7;
  public static final int LBRACE = 18;
  public static final int ELSE = 9;
  public static final int AND_ASSIGN = 48;
  public static final int CHARCONST = 64;
  public static final int WHILE = 10;
  public static final int OR_ASSIGN = 49;
  public static final int RBRACE = 19;
  public static final int NE = 28;
  public static final int MUL_ASSIGN = 43;
  public static final int STRING = 63;
  public static final int DEC = 37;
  public static final int STRUCT = 6;
  public static final int GT = 32;
  public static final int PARAOR = 26;
}

